### ISSUE TITLE
Incompatible version constraint 1.5.0 for Magento 2.4.5

### ISSUE THREAD

**Issue by Vinai** [colinmollenhour/php-redis-session-abstract#49]
The PHP 8.1 compatibility release 1.5.0 is not installable with Magento 2.4.5 because it uses the version constraint 
`"colinmollenhour/php-redis-session-abstract": "~1.4.5",`.

Looking at the CHANGELOG of php-redis-session-abstract from 1.4.5 to 1.5.0, but I do not see a reason why the minor version needs to be bumped to 5.  
Could you please tag the same release as 1.4.6?

**Comment by colinmollenhour** [comment]
Hi Vinai!

The reason I think was because of the change from del to unlink. unlink has been available since Redis 4.0 so one would have to be using a very old version of Redis to be affected. I suppose getting Magento to update the constraint to allow 1.5 is... difficult? Redis 4.0 has been EOL for a very long time so my guess is it is unlikely to be a problem but I just don't know.. Let me know what you think.

**Comment by Vinai** [comment]
I'm pretty sure Adobe won't change the dependency on `colinmollenhour/php-redis-session-abstract` in already released versions. It will be many months until 2.4.6, and probably also many months until the next patch release is made.

**Comment by colinmollenhour** [comment]
Ok, I backported the PHP 8.1 and Redis 6 Sentinel updates from 1.5.0 to 1.4.6 (skipping the UNLINK update for BC concerns).
https://github.com/colinmollenhour/php-redis-session-abstract/releases/tag/v1.4.6

**Comment by Vinai** [comment]
Thank you so much @colinmollenhour! This is a great :)
